# 1. Node.js의 공식 이미지 사용
FROM node:18-alpine

# 2. 작업 디렉토리 생성
WORKDIR app

# 3. 패키지 파일 복사
COPY package.json package-lock.json ./

# 4. 의존성 설치
RUN npm install

# 5. 애플리케이션 코드 복사
COPY . .

# 6. 컨테이너에서 앱 실행 시 사용하는 포트 지정
EXPOSE 3000

# 7. 애플리케이션 실행 명령어
CMD ["npm", "start"]