---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
data:
  password: MTIzNA== # base64로 인코딩 된 pw 1234 값 입력... 여기 토큰을 넣겠지??

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
data:
  password: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjMxMjM= # base64로 abcdefghijklmnopqrstuvwxyz123123 여기 토큰을 넣겠지??