#
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: maria-name

---
apiVersion: apps/v1
kind: Deployment # pod 여래개 쓸수있다.
metadata:
  name: mariadb-user-deployment
#  namespace: maria-name
spec: # 규격( 어떻게 만들지에 대해)
  replicas: 1 # pod 몇개 만들래
  selector:
    matchLabels:
      app: mariadb-user # 쿠버네티스 안에서 변수명으로 마리아디비라고 부르겟다
  template: # 템플릿
    metadata:
      labels:
        app: mariadb-user # 서비스에서 찾는 변수명
    spec: # pod 하나하나에 대한 내용
      containers:
        - name: mariadb-user
          image: mariadb # 도커허브에 있는 이미지
          ports:
            - containerPort: 3306 #default one
          env: # 환경설정 - 여기에 마리아-시크릿 넣음
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
          volumeMounts: # 여기에 마리아-컨피그맵 들어감
            - name: mariadb-initdb-config-user
              mountPath: /docker-entrypoint-initdb.d
      volumes: # 여기에 마리아-컨피그맵 들어감
        - name: mariadb-initdb-config-user
          configMap:
            name: mariadb-initdb-config-user
--- # 환경을 두개 달고 싶을때 구분자

apiVersion: v1
kind: Service
metadata:
  name: mariadb-user
#  namespace: maria-name
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306
  selector:
    app: mariadb-user