apiVersion: apps/v1
kind: Deployment # pod 여래개 쓸수있다.
metadata:
  name: second-service-deployment
spec: # 규격( 어떻게 만들지에 대해)
  replicas: 1 # pod 몇개 만들래
  selector:
    matchLabels:
      app: second-service # 쿠버네티스 안에서 변수명으로 마리아디비라고 부르겟다
  template: # 템플릿
    metadata:
      labels:
        app: second-service # 서비스에서 찾는 변수명
    spec: # pod 하나하나에 대한 내용
      containers:
        - name: second-service
          image: hheee/secondservice:k8.01 # 도커허브에 있는 이미지
          ports:
            - containerPort: 40002 #default one


--- # 환경을 두개 달고 싶을때 구분자

apiVersion: v1
kind: Service
metadata:
  name: second-service
spec:
  type: LoadBalancer
  ports:
    - port: 40002
      targetPort: 40002
  selector:
    app: second-service